---

name: Build and Test

on:
  push:
    branches:
    - dev # FIXME

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: microservice_a
          - workdir: microservice_b
          - workdir: microservice_c
    # permissions: we don't use cache
    #   contents: read
    #   packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: "build ${{matrix.workdir}} image"
        working-directory: "${{matrix.workdir}}"
        run: "./build.sh ${{github.sha}}"

  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: microservice_a
          - workdir: microservice_b
          - workdir: microservice_c
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

