---

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_PREFIX: "ghcr.io/${{ github.repository }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: microservice_a
          - workdir: microservice_b
          - workdir: microservice_c
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: "build ${{matrix.workdir}} image"
        working-directory: "${{matrix.workdir}}"
        run: "./build.sh ${{github.sha}}"

      - name: "run ${{matrix.workdir}} container"
        working-directory: "${{matrix.workdir}}"
        run: >-
          docker run
          --name ${{matrix.workdir}}__${{github.sha}}
          -d
          -P
          ${{ env.IMAGE_PREFIX }}/${{matrix.workdir}}:${{github.sha}}
      #
      # - name: "get logs for ${{matrix.workdir}} container"
      #   working-directory: "${{matrix.workdir}}"
      #   run: sleep 20s && docker logs ${{matrix.workdir}}__${{github.sha}}

      # - name: tests
      #   working-directory: "${{matrix.workdir}}"
      #   run: |
      #     docker cp ./test.py ${{matrix.workdir}}__${{github.sha}}:/tmp/
      #     docker run -it ${{matrix.workdir}}__${{github.sha}} pipenv install --dev
      #     docker run -it ${{matrix.workdir}}__${{github.sha}} pipenv run test $__CONTAINER_PORT -vv

      # - name: Log into registry ${{ env.REGISTRY }}
      #   uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #
      # - name: "pushing ${{matrix.workdir}} image"
      #   working-directory: "${{matrix.workdir}}"
      #   run: >-
      #    docker push
      #    ${{ env.REGISTRY }}/qb14-0985-4a94-939e-12e4f9cf1e8d/test-a-d/${{matrix.workdir}}:${{github.sha}}
